### ISSUE TITLE
Generic usb-modeswitch petbuild

### ISSUE THREAD

**Issue by woodenshoe-wi** [puppylinux-woof-CE/petbuilds#26]
From [http://www.murga-linux.com/puppy/viewtopic.php?p=992872&sid=089dd409d2e185f8840d93fe257b9361#992872](http://www.murga-linux.com/puppy/viewtopic.php?p=992872&sid=089dd409d2e185f8840d93fe257b9361#992872)
> Ok it's clear upup bionic and xenialpup should use the deb packages.
> 
> But here's a pet pkg compiled a bit differently, it's supposed to update older wce pups, however you might want to test it in a pristine install of upup bb, forcing this pet pkg into the system...

If the new pet works what are the needed changes and do you think it would it be feasible to add the changes to the common builds?

https://github.com/woodenshoe-wi/common32  
https://github.com/woodenshoe-wi/common64

Feel free to fork if you want, the only reason the common builds should not be in woof-CE is because they are very cut down and will not boot.

**Comment by wdlkmpx** [comment]
Oops i was not aware of this issue, i actually don't receive emails anymore, so i have to check the github page. I accidentally saw this after clicking a link i posted in https://github.com/puppylinux-woof-CE/woof-CE/pull/1207

The fix is in
https://github.com/puppylinux-woof-CE/petbuilds/commit/0e9b6bf7f53bbaf2d4bd5bc31bff70a271f73232

But it must be tested, this is something i can't test atm, so i was thinking of just editing the pkgs specs to use the deb pkgs.. in fact the change is done but it's not 'committed'

**Comment by wdlkmpx** [comment]
By the way, the raspup stuff needs some cleanup, many pet pkgs are too old, including usb-modeswitch

The first static app to be added to the common repos and raspup is busybox 1.28.3, but not this week.

**Comment by woodenshoe-wi** [comment]
Well, I can compile but I don't have the hardware to test...

Because "BUILD=" was not incremented in the petbuild the names are the same, but here are the recompiled pets:  
https://gitlab.com/woodenshoe-wi/petbuilds-out/raw/2b0e31701c8fe99aff29d51e2c905d05a31408cf/puppylinux/pet_packages-common32/usb-modeswitch-2.5.2-i686_common32.pet  
https://gitlab.com/woodenshoe-wi/petbuilds-out/raw/2b0e31701c8fe99aff29d51e2c905d05a31408cf/puppylinux/pet_packages-common64/usb-modeswitch-2.5.2-x86_64_common64.pet

The changes to the compiling logs can be viewed at https://gitlab.com/woodenshoe-wi/petbuilds-out/commit/2b0e31701c8fe99aff29d51e2c905d05a31408cf

Although I do receive emails from GitHub whenever I am @ mentioned or there are pull requests or issues opened for the woof-CE repo, I do not receive emails when changes are made to the petbuilds generic branch.  I am guessing it is because the generic branch is not the default branch.  If you don't receive emails when an issue is opened then I guess that won't work as a workaround either.

Feel free to use whatever solution works best, if that is using distro pkgs that is fine too.  I am just trying to keep the pets in sync with the petbuilds.

If you can run a 64 bit kernel you might be able to compile common64 pets from your favorite 32 bit distro using petbuilds-run_woof.sh

Instructions are at https://github.com/puppylinux-woof-CE/petbuilds/blob/generic/README.md

**Comment by woodenshoe-wi** [comment]
On the subject of raspup, it was never my intention to make and maintain a release (zip file download of a finished woof-CE build) but I figured if [Raspberry Pi build broken #1](https://github.com/puppylinux-woof-CE/woof-CE/issues/1) no one else could either.

I can't make a commitment to always fix things immediately, only when I have time, and if no one else steps up to make a raspup release I don't want to clutter up the ibiblio repo with pets that might never be used.  This didn't help either... https://github.com/puppylinux-woof-CE/woof-CE/issues/1147#issuecomment-369780678

There is still don570's [Fatdog Arm for Raspberry Pi 3](http://www.murga-linux.com/puppy/viewtopic.php?t=112937) and BarryK 's [Quirky Xerus 8.1.4 for Raspberry Pi2 and 3
](http://www.murga-linux.com/puppy/viewtopic.php?t=108132)

The only advantage that raspup would have other than being a "Puppy" (which may or may not be an advantage... :wink:) is that it should theoretically run on a Pi Zero (I only have a Pi 1 to test which has the same CPU chip).

**Comment by wdlkmpx** [comment]
The current usb-modeswitch package in common* is broken. woodenshoe-wi uploaded the patched version months ago.

This file
- [usb-modeswitch-2.5.2-i686_common32-2.pet_fake.zip](https://github.com/puppylinux-woof-CE/petbuilds/files/2466978/usb-modeswitch-2.5.2-i686_common32-2.pet_fake.zip)

should be uploaded to: to http://distro.ibiblio.org/puppylinux/pet_packages-common32/

This file 
- [usb-modeswitch-2.5.2-x86_64_common64-2.pet_fake.zip](https://github.com/puppylinux-woof-CE/petbuilds/files/2466979/usb-modeswitch-2.5.2-x86_64_common64-2.pet_fake.zip)

should be uploaded to: to http://distro.ibiblio.org/puppylinux/pet_packages-common64/


@peabee

**Comment by woodenshoe-wi** [comment]
I had not asked peabee to upload the pets because I didn't have the hardware to test them and I didn't know if the distro pkgs were going to be used instead.

If they work and don't need any additional changes, then yes, they should be uploaded.

**Comment by peabee** [comment]
Uploaded - but is numbering scheme right? -2 should be _2 and should leave common32 as last part of name....?? Also no _DOC ??

**Comment by woodenshoe-wi** [comment]
You might be right that the dash "-" should be an underscore "_" but the "common32" part is only there when no build number is specified to keep the petbuild scripts happy.

As for the _DOC pet, the old one should still be valid because the version has not changed, only one of the build options.

I could easily add the build number to the petbuild and re-run the build scripts.  Is that what you would prefer?

**Comment by wdlkmpx** [comment]
The pet pkg works fine, it was confirmed by itsmersh back in the day.
usb_modeswitch can be a tcl or a binary i think
Now it's a binary with libjim statically linked. jimtcl is redundant now..

Apparently the system is not (that) compatible with the compat distro cryptsetup

This file:
- www.01micko.com/wdlkmpx/tmp/cryptsetup-1.7.5-musl_static_armhf.pet
should be uploaded to:
- http://distro.ibiblio.org/puppylinux/arm/pet_packages-armv6/

This file:
- www.01micko.com/wdlkmpx/tmp/cryptsetup-1.7.5-musl_static_i686.pet
should be uploaded to:
- http://distro.ibiblio.org/puppylinux/pet_packages-common32/

This file:
- www.01micko.com/wdlkmpx/tmp/cryptsetup-1.7.5-musl_static_x86_64.pet
should be uploaded to:
- http://distro.ibiblio.org/puppylinux/pet_packages-common64/

These files:
- www.01micko.com/wdlkmpx/tmp/grub2_efi-2.02.2018.08-fd64.pet
- www.01micko.com/wdlkmpx/tmp/grub2_efi_fed-2.02.2018.08-fd64.pet
- http://murga-linux.com/puppy/viewtopic.php?mode=attach&id=115449
should be uploaded to:
- http://distro.ibiblio.org/puppylinux/pet_packages-noarch/

**Comment by peabee** [comment]
Done - though pets with name ....fd64 look odd in noarch....
