### ISSUE TITLE
tahr build fails

### ISSUE THREAD

**Issue by 01micko** [puppylinux-woof-CE/petbuilds#5]
```
evince failed to build
gtkdialog failed to build
inkscapelite failed to build
atkmm_static failed to build
gtkmm_static failed to build
pangomm_static failed to build
gparted failed to build
```

- evince - smclient - I believe this is aged code so looking for a patch
- gtkdialog - Can't locate Locale/Messages.pm in @INC - perl error, tahr bug
- inkscapelite - fatal error: freetype/ftoutln.h - maybe weird paths in tahr, or missing header
- *mm - thinking to not bother, if gtk+2 native versions are available - however they won't be static. IIRC, @pemasu  had them in raring
- gparted - see above
- _edit_ - osmo and sfontview now fixed

There were 10 others that were all relatively easy fixes (not committed yet). An interesting one was gnumeric. Ubuntu doesn't package pcretest at all, well maybe in some weird PPA, so I had to patch `configure` on the fly. Another thing with gnumeric is that the docs don't install, need dockbook-xml and rarian/scrollkeeper. I don't care, we don't use yelp anyway. So `make install` bugs out but everything relevant to run gnumeric is installed so we ignore the error and proceed to package.

Just FYI; I'll be taking a break for 2 weeks and check in occasionally to merge pull requests or check on updates.

**Comment by 01micko** [comment]
I am thinking to allow a 'distro specific' `ORDER` file so that failures can be omitted. Also, different `./configure` options could be specified.

Any thoughts :question:

**Comment by dimkr** [comment]
Tahr isn't reproducible anyway. AFAIK, you can't rebuild 6.0.2 using vanilla Woof. I think some manual tweaks were applied (e.g the wallpaper).

Fixing Tahr-specific problems without having all its configuration files in woof-CE is a bad way to go.

**Comment by mavrothal** [comment]
Yes, tahr has *a lot* of manual and uncommitted changes...

**Comment by 01micko** [comment]
Yes, that is true, but I did the same with Barry's woof but that was a 'private' repo. 

At least Phil is having a a go.. something which I haven't had time for lately. Perhaps some subtle coercion would help.

**Comment by 01micko** [comment]
> I am thinking to allow a 'distro specific' `ORDER` file so that failures can be omitted

Dumb idea. I think I'll just create branches and 'master' will just be a 'readme' kind of like how Junjiro does it with aufs.
